"""
Django settings for meteorological project.

Generated by 'django-admin startproject' using Django 2.2.13.

For more information on this file, see
https://docs.djangoproject.com/en/2.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/2.2/ref/settings/
"""

import os

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

# 使用 MySQL 时用 PyMySQL 替代 mysqlclient（需安装: pip install pymysql）
# 若仍报 mysqlclient 1.4.3 required，可先卸载: pip uninstall mysqlclient
try:
    import pymysql
    pymysql.install_as_MySQLdb()
    # 让 Django 的版本检查通过（Django 要求 mysqlclient>=1.4.3，PyMySQL 报的版本会被误判）
    if hasattr(pymysql, 'version_info'):
        pymysql.version_info = (1, 4, 3, 'final', 0)
except ImportError:
    pass


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/2.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'CHANGE_ME'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['*','192.168.10.3']


# Application definition

INSTALLED_APPS = [
    'simpleui',  # 必须在 django.contrib.admin 之前，替换默认后台界面
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'app.apps.AppConfig',
    'DjangoUeditor',
]

# ---------- django-simpleui 后台（https://github.com/newpanjing/simpleui）----------
SIMPLEUI_ANALYSIS = False
SIMPLEUI_HOME_INFO = False
SIMPLEUI_HOME_QUICK = True
SIMPLEUI_HOME_ACTION = True
# 内置主题：element 清爽现代；也可换 admin.lte.css、dark.green.css 等
SIMPLEUI_DEFAULT_THEME = 'element.css'
SIMPLEUI_CONFIG = {
    'system_keep': True,
    'dynamic': True,
}
MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    # 'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'meteorological.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR ,'templates')]
        ,
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'app.context_processors.global_context'

            ],
        },
    },
]

WSGI_APPLICATION = 'meteorological.wsgi.application'


# Database
# https://docs.djangoproject.com/en/2.2/ref/settings/#databases
# 数据库类型与连接信息在 meteorological/config.py 中配置（sqlite / mysql）
from meteorological import config
DATABASES = config.DATABASES



# Password validation
# https://docs.djangoproject.com/en/2.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/2.2/topics/i18n/

LANGUAGE_CODE = 'zh-hans'
TIME_ZONE = 'Asia/Shanghai'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/2.2/howto/static-files/

STATIC_URL = '/static/'
STATICFILES_DIRS =  (
    os.path.join(BASE_DIR,'static'),
)

# 图片储存根路径
MEDIA_ROOT = os.path.join(BASE_DIR,'media')
# 图片访问url
MEDIA_URL = '/IMG/'