# Generated by Django 2.2.4 on 2022-11-22 05:46

import DjangoUeditor.models
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Goods',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=128, verbose_name='标题')),
                ('date', models.DateField(verbose_name='日期')),
                ('img', models.ImageField(upload_to='news/img/', verbose_name='图像')),
                ('content', DjangoUeditor.models.UEditorField(default='', verbose_name='内容')),
                ('view', models.IntegerField(default=0, verbose_name='浏览次数')),
                ('price', models.IntegerField(default=100, verbose_name='价格')),
            ],
            options={
                'verbose_name_plural': '商品信息',
            },
        ),
        migrations.CreateModel(
            name='Kind',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=128, verbose_name='名字')),
            ],
            options={
                'verbose_name_plural': '商品类别',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=128, verbose_name='姓名')),
                ('tel', models.CharField(max_length=128, verbose_name='手机')),
                ('password', models.CharField(max_length=128, verbose_name='密码')),
            ],
            options={
                'verbose_name_plural': '用户表管理',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('num', models.IntegerField(default=1, verbose_name='数量')),
                ('today', models.DateField(auto_now_add=True, verbose_name='下单日期')),
                ('uuid', models.CharField(default=uuid.UUID('b3101d8e-c65c-4fb2-b71e-d1e3958e07cd'), max_length=64, verbose_name='订单号')),
                ('goods', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app.Goods', verbose_name='商品')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.User', verbose_name='用户')),
            ],
            options={
                'verbose_name': '订单',
                'verbose_name_plural': '订单',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Goods', verbose_name='商品')),
                ('uid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.User', verbose_name='用户')),
            ],
            options={
                'verbose_name_plural': '收藏管理',
            },
        ),
        migrations.AddField(
            model_name='goods',
            name='kind',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Kind', verbose_name='类别'),
        ),
    ]
