# Generated by Django 2.2.14 on 2024-12-24 11:11

import DjangoUeditor.models
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='id')),
                ('title', models.CharField(max_length=64, verbose_name='标题')),
                ('tags', models.CharField(max_length=128, verbose_name='标签')),
                ('content', DjangoUeditor.models.UEditorField(default='内容', verbose_name='内容')),
                ('date', models.DateTimeField(auto_now=True, verbose_name='发布时间')),
                ('img', models.CharField(default='', max_length=128, verbose_name='图片')),
            ],
            options={
                'verbose_name': '文章管理',
                'verbose_name_plural': '文章管理',
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('content', models.CharField(max_length=1024, verbose_name='评论内容')),
                ('date', models.DateField(auto_now_add=True, verbose_name='评论时间')),
            ],
            options={
                'verbose_name': '商品评价管理',
                'verbose_name_plural': '商品评价管理',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='CommentBlog',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('content', models.CharField(max_length=1024, verbose_name='评论内容')),
                ('date', models.DateField(auto_now_add=True, verbose_name='评论时间')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Blog', verbose_name='文章')),
            ],
            options={
                'verbose_name': '文章评论管理',
                'verbose_name_plural': '文章评论管理',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='Datasets',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=128, verbose_name='类别')),
                ('img', models.CharField(max_length=128, verbose_name='图片')),
            ],
            options={
                'verbose_name_plural': '毒蘑菇数据集管理',
            },
        ),
        migrations.CreateModel(
            name='Datasets1',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('img', models.CharField(max_length=128, verbose_name='图片')),
            ],
            options={
                'verbose_name_plural': '山货数据集管理',
            },
        ),
        migrations.CreateModel(
            name='PredictHistory',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('kind', models.CharField(max_length=128, verbose_name='类别')),
                ('img', models.CharField(max_length=128, verbose_name='图片')),
                ('time', models.DateField(auto_now_add=True, verbose_name='时间')),
            ],
            options={
                'verbose_name': '蘑菇识别管理',
                'verbose_name_plural': '蘑菇识别管理',
                'ordering': ['-time'],
            },
        ),
        migrations.CreateModel(
            name='PredictHistory1',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('img', models.CharField(max_length=128, verbose_name='图片')),
                ('time', models.DateField(auto_now_add=True, verbose_name='时间')),
            ],
            options={
                'verbose_name': '山货识别管理',
                'verbose_name_plural': '山货识别管理',
                'ordering': ['-time'],
            },
        ),
        migrations.AlterModelOptions(
            name='goods',
            options={'verbose_name_plural': '商品管理'},
        ),
        migrations.AlterModelOptions(
            name='kind',
            options={'verbose_name_plural': '山货类别管理'},
        ),
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ['id'], 'verbose_name': '订单管理', 'verbose_name_plural': '订单管理'},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name_plural': '用户管理'},
        ),
        migrations.RemoveField(
            model_name='goods',
            name='view',
        ),
        migrations.AlterField(
            model_name='order',
            name='uuid',
            field=models.CharField(default=uuid.UUID('92eb2967-3384-41a0-9cd5-8cd682268149'), max_length=64, verbose_name='订单号'),
        ),
        migrations.DeleteModel(
            name='Like',
        ),
        migrations.AddField(
            model_name='predicthistory1',
            name='kind',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Kind', verbose_name='类别'),
        ),
        migrations.AddField(
            model_name='predicthistory1',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.User', verbose_name='用户'),
        ),
        migrations.AddField(
            model_name='predicthistory',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.User', verbose_name='用户'),
        ),
        migrations.AddField(
            model_name='datasets1',
            name='kind',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Kind', verbose_name='类别'),
        ),
        migrations.AddField(
            model_name='commentblog',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.User', verbose_name='用户'),
        ),
        migrations.AddField(
            model_name='comment',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Goods', verbose_name='item'),
        ),
        migrations.AddField(
            model_name='comment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.User', verbose_name='用户'),
        ),
        migrations.AddField(
            model_name='blog',
            name='kind',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Kind', verbose_name='类别'),
        ),
        migrations.AddField(
            model_name='blog',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.User', verbose_name='发布人'),
        ),
    ]
