# Generated by Django 2.2.14 on 2024-12-30 07:13

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20241224_1911'),
    ]

    operations = [
        migrations.AddField(
            model_name='kind',
            name='img',
            field=models.ImageField(null=True, upload_to='img/', verbose_name='图片'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='img',
            field=models.ImageField(null=True, upload_to='img/', verbose_name='图片'),
        ),
        migrations.AlterField(
            model_name='datasets',
            name='img',
            field=models.ImageField(null=True, upload_to='img/', verbose_name='图片'),
        ),
        migrations.AlterField(
            model_name='datasets1',
            name='img',
            field=models.ImageField(null=True, upload_to='img/', verbose_name='图片'),
        ),
        migrations.AlterField(
            model_name='order',
            name='uuid',
            field=models.CharField(default=uuid.UUID('3cdd5fc6-6afd-4304-881c-82005583fc52'), max_length=64, verbose_name='订单号'),
        ),
        migrations.AlterField(
            model_name='predicthistory',
            name='img',
            field=models.ImageField(null=True, upload_to='img/', verbose_name='图片'),
        ),
    ]
