# Generated by Django 2.2.14 on 2024-12-30 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20241230_1513'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='goods',
            name='kind',
        ),
        migrations.RemoveField(
            model_name='order',
            name='goods',
        ),
        migrations.RemoveField(
            model_name='order',
            name='user',
        ),
        migrations.AlterField(
            model_name='datasets',
            name='name',
            field=models.CharField(choices=[('无毒蘑菇', '无毒蘑菇'), ('有毒蘑菇', '有毒蘑菇')], max_length=128, verbose_name='类别'),
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
        migrations.DeleteModel(
            name='Goods',
        ),
        migrations.DeleteModel(
            name='Order',
        ),
    ]
