# Generated by Django 2.2.14 on 2024-12-30 08:44

import DjangoUeditor.models
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20241230_1643'),
    ]

    operations = [
        migrations.CreateModel(
            name='Goods',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=128, verbose_name='标题')),
                ('date', models.DateField(auto_now_add=True, verbose_name='日期')),
                ('img', models.ImageField(upload_to='news/img/', verbose_name='图像')),
                ('content', DjangoUeditor.models.UEditorField(default='', verbose_name='内容')),
                ('price', models.IntegerField(default=100, verbose_name='价格')),
                ('kind', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Kind', verbose_name='类别')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.User', verbose_name='用户')),
            ],
            options={
                'verbose_name_plural': '商品管理',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('num', models.IntegerField(default=1, verbose_name='数量')),
                ('today', models.DateField(auto_now_add=True, verbose_name='下单日期')),
                ('uuid', models.CharField(default=uuid.UUID('6fde3570-b371-4bc4-a253-d51b6512d248'), max_length=64, verbose_name='订单号')),
                ('goods', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app.Goods', verbose_name='商品')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.User', verbose_name='用户')),
            ],
            options={
                'verbose_name': '订单管理',
                'verbose_name_plural': '订单管理',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('content', models.CharField(max_length=1024, verbose_name='评论内容')),
                ('date', models.DateField(auto_now_add=True, verbose_name='评论时间')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Goods', verbose_name='item')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.User', verbose_name='用户')),
            ],
            options={
                'verbose_name': '商品评价管理',
                'verbose_name_plural': '商品评价管理',
                'ordering': ['-date'],
            },
        ),
    ]
