# Generated by Django 2.2.14 on 2025-12-29 03:33

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_comment_goods_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='uuid',
            field=models.CharField(default=uuid.UUID('638232f4-0de3-4f25-830e-612091fa3f24'), max_length=64, verbose_name='订单号'),
        ),
    ]
