# Generated by Django 2.2.14 on 2025-12-29 07:19

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20251229_1133'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='uuid',
            field=models.CharField(default=uuid.UUID('46c46c65-50a3-4fd8-8654-1d6031af65e7'), max_length=64, verbose_name='订单号'),
        ),
    ]
