# Generated by Django 4.2 on 2026-02-20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_auto_20251229_1519'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='sentiment',
            field=models.CharField(
                choices=[('positive', '正面'), ('negative', '负面'), ('neutral', '中性')],
                default='neutral',
                max_length=20,
                verbose_name='情感倾向'
            ),
        ),
        migrations.AddField(
            model_name='comment',
            name='sentiment_confidence',
            field=models.FloatField(default=0.5, verbose_name='情感置信度'),
        ),
        migrations.AddField(
            model_name='commentblog',
            name='sentiment',
            field=models.CharField(
                choices=[('positive', '正面'), ('negative', '负面'), ('neutral', '中性')],
                default='neutral',
                max_length=20,
                verbose_name='情感倾向'
            ),
        ),
        migrations.AddField(
            model_name='commentblog',
            name='sentiment_confidence',
            field=models.FloatField(default=0.5, verbose_name='情感置信度'),
        ),
    ]
